using System.Collections.Generic;

namespace HVR.Basis.AvatarOptimizer
{
    // Based on d4rkAvatarOptimizer.cs
    internal class d4rkOptmizerExtractions
    {
        // blendshape names come from https://www.deviantart.com/xoriu/art/MMD-Facial-Expressions-Chart-341504917
        internal static HashSet<string> MMDBlendShapes = new HashSet<string>()
        {
            "まばたき", "Blink",
            "笑い", "Smile",
            "ウィンク", "Wink",
            "ウィンク右", "Wink-a",
            "ウィンク２", "Wink-b",
            "ｳｨﾝｸ２右", "Wink-c",
            "なごみ", "Howawa",
            "はぅ", "> <",
            "びっくり", "Ha!!!",
            "じと目", "Jito-eye",
            "ｷﾘｯ", "Kiri-eye",
            "はちゅ目", "O O",
            "星目", "EyeStar",
            "はぁと", "EyeHeart",
            "瞳小", "EyeSmall",
            "瞳縦潰れ", "EyeSmall-v",
            "光下", "EyeUnderli",
            "恐ろしい子！", "EyeFunky",
            "ハイライト消", "EyeHi-off",
            "映り込み消", "EyeRef-off",
            "喜び", "Joy",
            "わぉ?!", "Wao?!",
            "なごみω", "Howawa ω",
            "悲しむ", "Wail",
            "敵意", "Hostility",
            "あ", "a",
            "い", "i",
            "う", "u",
            "え", "e",
            "お", "o",
            "あ２", "a 2",
            "ん", "n",
            "▲", "Mouse_1",
            "∧", "Mouse_2",
            "□", "□",
            "ワ", "Wa",
            "ω", "Omega",
            "ω□", "ω□",
            "にやり", "Niyari",
            "にやり２", "Niyari2",
            "にっこり", "Smile",
            "ぺろっ", "Pero",
            "てへぺろ", "Bero-tehe",
            "てへぺろ２", "Bero-tehe2",
            "口角上げ", "MouseUP",
            "口角下げ", "MouseDW",
            "口横広げ", "MouseWD",
            "歯無し上", "ToothAnon",
            "歯無し下", "ToothBnon",
            "真面目", "Serious",
            "困る", "Trouble",
            "にこり", "Smily",
            "怒り", "Get angry",
            "上", "UP",
            "下", "Down",
            "Grin",
            "Blink",
            "Blink Happy",
            "Pupil",
            "Wink",
            "Wink Right",
            "Wink 2",
            "Wink 2 Right",
            "Calm",
            "Stare",
            "Cheerful",
            "Sadness",
            "Anger",
            "Upper",
            "Lower"
        };
    }
}